[build-system]
requires = ['setuptools']
build-backend = "setuptools.build_meta"

[project]
name = "javalang"
version = "0.0.1"

[tool.setuptools.packages.find]
where = ['src']
include = ['javalang*']
exclude = ['javalang.man*']
namespaces = false
